модуль 1, задания 1-5
js-tasks-ru/jsbasic-20210906-2_dmitry-zakharov5 pull request #2
Opened 2021-09-15 17:43 UTC by sasukeuchiwa666

2021-09-15 17:44 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-15 19:36 UTC, SinimaWath requested changes

2021-09-15 19:36 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  }
Давай все таки поправим отступы, чтобы все было на разных уровнях

2021-09-15 19:36 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  if (modifiedString.includes('xbet') || modifiedString.includes('xxx')){
modifiedString.includes('xbet') || modifiedString.includes('xxx') - это boolean, поэтому if здесь лишний, давай без него

2021-09-15 19:36 UTC, SinimaWath commented on 1-module/5-task/index.js
> +   return truncatedStr
Давай без временной переменной: `return str.slice(0, maxlength - 1) + '…'`

2021-09-16 13:13 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-16 20:10 UTC, SinimaWath approved these changes

2021-09-16 20:10 UTC, merged